### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by gnana997** [danielegrattarola/twitter-sentiment-cnn#10]
Traceback (most recent call last):
  File "twitter-sentiment-cnn.py", line 147, in <module>
    x, y, vocabulary, vocabulary_inv = load_data(FLAGS.reduced_dataset)
  File "C:\Users\gnana\Desktop\twitter-sentiment-cnn\data_helpers.py", line 166, in load_data
    vocabulary, vocabulary_inv = build_vocab()
  File "C:\Users\gnana\Desktop\twitter-sentiment-cnn\data_helpers.py", line 119, in build_vocab
    vocabulary = {x:i for x, i in voc}
  File "C:\Users\gnana\Desktop\twitter-sentiment-cnn\data_helpers.py", line 119, in <dictcomp>
    vocabulary = {x:i for x, i in voc}
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by danielegrattarola** [comment]
Can you give me a little more details on how to reproduce this? 
By looking at the stack trace it's probably a setup error, make sure to follow the installation instructions in the README.

**Comment by shineangelic** [comment]
I could solve this removing blank lines in vocab.csv and vocab_inv.csv
