### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Alex-Nguyen** [danielegrattarola/twitter-sentiment-cnn#11]
Hi, I got the following error
Traceback (most recent call last):
  File "twitter-sentiment-cnn.py", line 195, in <module>
    h_pool = tf.concat(3, pooled_outputs)
  File "/Users/vinhtngu/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1061, in concat
    dtype=dtypes.int32).get_shape(
  File "/Users/vinhtngu/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 611, in convert_to_tensor
    as_ref=False)
  File "/Users/vinhtngu/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/vinhtngu/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/vinhtngu/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Users/vinhtngu/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 376, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/Users/vinhtngu/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

Do you know how can I fix this? Thank you very much

**Comment by danielegrattarola** [comment]
Hi,
Can you give me more info on the python and TF versions that you are using? Also did you change anything in the code?

**Comment by Alex-Nguyen** [comment]
Hello,
I'm using the latest version of TF 1.3. Python v 2.7.19.  The rest of the code I follow your instruction. The setup works fine. Here is the code
Last login: Sun Sep 24 23:39:30 on ttys000
Vinhs-MacBook-Air:~ vinhtngu$ cd twitter-sentiment-cnn
Vinhs-MacBook-Air:twitter-sentiment-cnn vinhtngu$ source ~/tensorflow/bin/activate
(tensorflow) Vinhs-MacBook-Air:twitter-sentiment-cnn vinhtngu$ python twitter-sentiment-cnn.py

=======================================================
======================= START! ========================
=======================================================
Preprocessing...
	data_helpers: loading positive examples...
	data_helpers: [OK]
	data_helpers: loading negative examples...
	data_helpers: [OK]
	data_helpers: cleaning strings...
data_helpers: [OK]
	data_helpers: generating labels...
	data_helpers: [OK]
	data_helpers: concatenating labels...
	data_helpers: [OK]
	data_helpers: padding strings...
	data_helpers: [OK]
	data_helpers: building vocabulary...
	data_helpers: [OK]
	data_helpers: building processed datasets...
data_helpers: [OK]
2017-09-25 11:08:03.675752: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-25 11:08:03.675806: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-25 11:08:03.675813: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-25 11:08:03.675819: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.

Flags:
	batch_size = 100
	checkpoint_freq = 1
	custom_input = 
	embedding_size = 128
	epochs = 3
	evaluate_batch = False
	filter_sizes = 3,4,5
	load = 
	num_filters = 128
	reduced_dataset = 1
	save = False
	test_data_ratio = 10
	train = False
	valid_freq = 1

Dataset:
	Train set size = 1420766
	Test set size = 157862
	Vocabulary size = 274562
	Input layer size = 117
	Number of classes = 2

Output folder: /Users/vinhtngu/twitter-sentiment-cnn/output/run20170925-110515
Traceback (most recent call last):
  File "twitter-sentiment-cnn.py", line 195, in <module>
    h_pool = tf.concat(3, pooled_outputs)
  File "/Users/vinhtngu/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1061, in concat
    dtype=dtypes.int32).get_shape(
  File "/Users/vinhtngu/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 611, in convert_to_tensor
    as_ref=False)
  File "/Users/vinhtngu/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/vinhtngu/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/vinhtngu/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Users/vinhtngu/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 376, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/Users/vinhtngu/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

I did not change anything in the code. This is my learning process. Thank you very much for your help

**Comment by danielegrattarola** [comment]
```sh
phait at twitter-sentiment-cnn $ python twitter-sentiment-cnn.py 
======================= START! ========================
	data_helpers: loading positive examples...
	data_helpers: [OK]
	data_helpers: loading negative examples...
	data_helpers: [OK]
	data_helpers: cleaning strings...
	data_helpers: [OK]
	data_helpers: generating labels...
	data_helpers: [OK]
	data_helpers: concatenating labels...
	data_helpers: [OK]
	data_helpers: padding strings...
	data_helpers: [OK]
	data_helpers: building vocabulary...
	data_helpers: [OK]
	data_helpers: building processed datasets...
	data_helpers: [OK]

Flags:
	batch_size = 100
	checkpoint_freq = 1
	custom_input = 
	device = cpu
	embedding_size = 128
	epochs = 3
	evaluate_batch = False
	filter_sizes = 3,4,5
	load = None
	num_filters = 128
	reduced_dataset = 1
	save = False
	save_protobuf = False
	test_data_ratio = 10
	train = False
	valid_freq = 1

Dataset:
	Train set size = 1420766
	Test set size = 157862
	Vocabulary size = 274562
	Input layer size = 117
	Number of classes = 2

Output folder: /home/phait/dev/twitter-sentiment-cnn/output/run20170925-181129
2017-09-25 18:12:44.956340: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-25 18:12:44.956358: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-25 18:12:44.956380: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-25 18:12:44.956384: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-25 18:12:44.956391: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-09-25 18:12:45.048084: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-09-25 18:12:45.048361: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 1050
major: 6 minor: 1 memoryClockRate (GHz) 1.493
pciBusID 0000:01:00.0
Total memory: 3.95GiB
Free memory: 2.98GiB
2017-09-25 18:12:45.048392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-09-25 18:12:45.048398: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-09-25 18:12:45.048426: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0)
Data processing OK, creating network...
```

Looks like the only difference between our output (besides the crash) is the save_protobuf flag, which was added in a recent commit. 
Did you pull recently?

Cheers, 
Daniele

**Comment by Alex-Nguyen** [comment]
Yes, I pulled and run everything two days ago.  How to solve it? Thanks

**Comment by danielegrattarola** [comment]
Sorry, but since it works on my machine I can be of little help.   
Try to pull/clone again, or check by hand if your code is up to date with the latest repo version. 
Also, I notice that you are using a venv to run TF, so check if all versions of TF on your machine are up to date (`tensorflow-gpu==1.3.0`).

That's the most I can do.

**Comment by Alex-Nguyen** [comment]
I solved it by updating python version 2.7.10 -> 2.7.14 then install tensorflow as "native" pip command. Thank for your suggestion. In addition.
git clone https://gitlab.com/danielegrattarola/twitter-sentiment-cnn.git did not pull the latest source code. It's better to  download it

**Comment by danielegrattarola** [comment]
Good to know, I'm glad it works

**Comment by deepkshikha** [comment]
@Alex-Nguyen I am getting same error. I have installed tensorflow as native pip command only. An python version is 2.7.12 Can you suggest something

**Comment by Alex-Nguyen** [comment]
I just updated python version 2.7.14 and then i worked
