### ISSUE TITLE
NameError: global name 'Counter' is not defined

### ISSUE THREAD

**Issue by raulium** [danielegrattarola/twitter-sentiment-cnn#12]
https://github.com/danielegrattarola/twitter-sentiment-cnn/blob/d4b20c995b75cd43b8d52a6be5e24e1537fa53d3/vocab_builder.py#L15

MacOS Sierra, python 2.7.  Performed `sudo -H pip install --upgrade tensorflow` and `sudo -H pip install tqdm`

Followed instructions and all worked until running `python vocab_builder.py`
Script output:

```python
$ python vocab_builder.py 
vocab_builder: loading...
	data_helpers: loading positive examples...
	data_helpers: [OK]
	data_helpers: loading negative examples...
	data_helpers: [OK]
	data_helpers: cleaning strings...
	data_helpers: [OK]
	data_helpers: generating labels...
	data_helpers: [OK]
	data_helpers: concatenating labels...
	data_helpers: [OK]
vocab_builder: padding...
vocab_builder: building vocabularies...
Traceback (most recent call last):
  File "vocab_builder.py", line 29, in <module>
    vocabulary, vocabulary_inv = build_vocab(sentences_padded)
  File "vocab_builder.py", line 15, in build_vocab
    word_counts = Counter(itertools.chain(*sentences))
NameError: global name 'Counter' is not defined
```

**Comment by danielegrattarola** [comment]
I accidentally removed the import, my bad. 
Fixed by commit 65880bdc2636c57a0ef70c79bdb83daba3bc5fc9

Thanks
