### ISSUE TITLE
Can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by subasish** [danielegrattarola/twitter-sentiment-cnn#5]
Running it in python3. Getting the following error message:

```
python3 vocab_builder.py
vocab_builder: loading...
	data_helpers: loading positive examples...
	data_helpers: [OK]
	data_helpers: loading negative examples...
	data_helpers: [OK]
Traceback (most recent call last):
  File "vocab_builder.py", line 25, in <module>
    sentences, labels = load_data_and_labels(1)  # 1 is passed so that load_data_and_labels() will parse the whole dataset
  File "/Users/subasishdas1/Desktop/RCodeData/twitter-sentiment-cnn/data_helpers.py", line 57, in load_data_and_labels
    positive_examples = sample_list(positive_examples, reduced_dataset)
  File "/Users/subasishdas1/Desktop/RCodeData/twitter-sentiment-cnn/data_helpers.py", line 39, in sample_list
    return random.sample(list, len(list)/dividend)
  File "//anaconda/lib/python3.5/random.py", line 316, in sample
    result = [None] * k
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by danielegrattarola** [comment]
The problem is this line:
```return random.sample(list, len(list)/dividend)```

In Python 3 the division operator returns a `float` if there is a carry, whereas in Python 2 it returns an `int` regardless.
Try running the code with Python 2.7, at the moment there is no guaranteed Python 3 support.

Cheers,
Daniele

**Comment by jcbain** [comment]
you can rewrite the sample_list function to force the k argument to be an int like so

```python
def sample_list(list, dividend):
    """
    Returns 1/dividend-th of the given list, randomply sampled.
    """
    k = int(len(list)/dividend)
    return random.sample(list, k)
```
